### ISSUE TITLE
Add Databases

### ISSUE THREAD

**Issue by DraculaLP** [gitipexa/scripts#1]
Add MySQL, MongoDB, MariaDB

**Comment by gitipexa** [comment]
As Docker?

**Comment by gitipexa** [comment]
Working...

**Comment by gitipexa** [comment]
✅MariaDB , MariaDB Docker, MySQL
📝Working on MongoDB, MonoDB Docker, MySQL

**Comment by gitipexa** [comment]
Adding MongoDB Docker :)
